Repository jenkinsci/pipeline-groovy-lib-plugin, pull requests merged in 2022-07, with the labels that each got.

#7 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#8 bump bom to 1500.ve4d05cd32975
  pom.xml
Labels: developer

#9 update dependabot.yml
  .github/dependabot.yml
Labels: chore

#3 [fix JENKINS-66898] make the cache thread safe
  src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryAdder.java
  src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingCleanup.java
  src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfiguration.java
  src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfiguration/config.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfiguration/help-forceDelete.html
  src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryAdderTest.java
  src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryCachingConfigurationTest.java
Labels: bug
