Repository jenkinsci/pipeline-groovy-lib-plugin, pull requests merged in 2022-12, with the labels that each got.

#35 Remove unnecessary SpotBugs exclusion
  src/main/java/org/jenkinsci/plugins/workflow/libs/SCMSourceRetriever.java
Labels: chore

#40 Adapt test for git plugin 5.0
  src/test/java/org/jenkinsci/plugins/workflow/libs/LibraryStepTest.java
Labels: developer

#42 Update baseline to 2.361.4+, POM
  .github/CODEOWNERS
  .github/release-drafter.yml
  Jenkinsfile
  pom.xml
Labels: dependencies
